.nh
.TH "DEVPREFLIGHT" "1" "Oct 2025" "DevPreflight 0.1.0" "DevPreflight Manual"

.SH NAME
devpreflight-completion - Generate shell completion script


.SH SYNOPSIS
\fBdevpreflight completion [bash|zsh|fish|powershell]\fP


.SH DESCRIPTION
Generate shell completion script for DevPreflight.

.PP
To load completions:

.PP
Bash:
  $ source <(devpreflight completion bash)

.PP
# To load completions for each session, execute once:
  # Linux:
  $ devpreflight completion bash > /etc/bash_completion.d/devpreflight
  # macOS:
  $ devpreflight completion bash > /usr/local/etc/bash_completion.d/devpreflight

.PP
Zsh:
  # If shell completion is not already enabled in your environment,
  # you will need to enable it. You can execute the following once:
  $ echo "autoload -U compinit; compinit" >> ~/.zshrc

.PP
# To load completions for each session, execute once:
  $ devpreflight completion zsh > "${fpath[1]}/_devpreflight"

.PP
# You will need to start a new shell for this setup to take effect.

.PP
Fish:
  $ devpreflight completion fish | source

.PP
# To load completions for each session, execute once:
  $ devpreflight completion fish > ~/.config/fish/completions/devpreflight.fish

.PP
PowerShell:
  PS> devpreflight completion powershell | Out-String | Invoke-Expression

.PP
# To load completions for every new session, run:
  PS> devpreflight completion powershell > devpreflight.ps1
  # and source this file from your PowerShell profile.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is .devpreflightrc.yml)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	enable verbose output


.SH EXAMPLE
.EX
  # Generate bash completion
  devpreflight completion bash > /etc/bash_completion.d/devpreflight

  # Generate zsh completion
  devpreflight completion zsh > "${fpath[1]}/_devpreflight"

  # Generate fish completion
  devpreflight completion fish > ~/.config/fish/completions/devpreflight.fish
.EE


.SH SEE ALSO
\fBdevpreflight(1)\fP


.SH HISTORY
7-Oct-2025 Auto generated by spf13/cobra
